name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      testRepo:
        description: 'location'
        required: false
      solutionRepo:
        description: 'location'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    name: ${{ github.event.inputs.name }}
    steps:
    - uses: actions/checkout@v2
    - name: Run challenge (Node.js ${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clone tests repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.testRepo }}
        path: ./
    - name: Install dependencies
      run: npm ci
      working-directory: ./
    - name: Clone app repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.solutionRepo }}
        path: ./_cloned-app
    - name: Run test on cloned app
      run: npm run test
      working-directory: ./
