name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      repo:
        description: 'location'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    name: ${{ github.event.inputs.name }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests (Node.js ${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: a1a1
      run: npm i
      working-directory: ./.github/workflows/first/
    - name: Also clone wiki # work around for West or Github Checkout Action limitation of private repos
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        path: ./.github/workflows/first/app
    - name: c2c2c2c2
      run: npm run test
      working-directory: ./.github/workflows/first/
